//
// CNAddress.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

class CNAddress : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "Address"
	}

	// MARK: Properties

	@NSManaged var city: String?

	@NSManaged var country: String?

	@NSManaged var stateAbbrevation: String?

	@NSManaged var line2: String?

	@NSManaged var line1: String?

	@NSManaged var zipCode: NSNumber?

	var valid: Bool? {
		get { return self["valid"] as? Bool }
		set { return self["valid"] = newValue }
	}

	@NSManaged var location: PFGeoPoint?

}