//
// CNItem.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

class CNItem : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "Item"
	}

	// MARK: Properties

	@NSManaged var gender: String?

	@NSManaged var brand: CNBrand?

	@NSManaged var soldPrice: NSNumber?

	@NSManaged var purchasePrice: NSNumber?

	@NSManaged var soldDate: NSDate?

	@NSManaged var brandName: String?

	@NSManaged var words: [AnyObject]?

	@NSManaged var photo: PFFile?

	@NSManaged var shortDesc: String?

	@NSManaged var listPrice: NSNumber?

	@NSManaged var user: CNUser?

}