//
// CNOrgInvite.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

class CNOrgInvite : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "OrgInvite"
	}

	// MARK: Properties

	@NSManaged var orgName: String?

	@NSManaged var toEmail: String?

	@NSManaged var state: String?

	@NSManaged var org: CNOrg?

	@NSManaged var fromUser: CNUser?

}