//
// CNOrgMembership.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

class CNOrgMembership : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "OrgMembership"
	}

	// MARK: Properties

	@NSManaged var orgRole: NSNumber?

	@NSManaged var org: CNOrg?

	@NSManaged var user: CNUser?

}