//
// CNUser.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

class CNUser : PFUser {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	// MARK: Properties

	@NSManaged var volunteeringEvents: [CNSaleEvent]?

	@NSManaged var firstName: String?

	@NSManaged var lastName: String?

	@NSManaged var profileImage: PFFile?

	@NSManaged var phone: NSNumber?

	@NSManaged var address: CNAddress?

	@NSManaged var coordinatingEvents: [CNEvent]?

	@NSManaged var orgMemberships: [CNOrgMembership]?

}