//
// Parse+Subclasses.swift
//
// Auto-generated by GSParseSchema on 07/14/15.
//

import Parse

extension Parse {

	// Call this function before 'Parse.setApplicationId(applicationId: String, clientKey: String)' in your AppDelegate
	class func registerSubclasses() {
		CNAddress.registerSubclass()
		CNOrgMembership.registerSubclass()
		CNBrand.registerSubclass()
		CNOrgInvite.registerSubclass()
		CNUser.registerSubclass()
		CNItem.registerSubclass()
		CNOrg.registerSubclass()
		CNEvent.registerSubclass()
	}
}